version: "3.8"

services:

  mongo:
    image: mongo:6.0
    container_name: mongo-container
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: Cis
    volumes:
      - ./init:/docker-entrypoint-initdb.d  
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: sa         
      ME_CONFIG_BASICAUTH_PASSWORD: sa         
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
