version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-container  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Cis
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    volumes:
      - mysql-data:/var/lib/mysql  
    ports:
      - "3306:3306"  
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container  
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql-data:  
    name: mysql-data-volume

networks:
  app-network:  
